config/routes.rb
require 'sidekiq/web'

EmpiricalGrammar::Application.routes.draw do
  use_doorkeeper

  # authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  resources :admins, only: [:show], format: 'json' do
    resources :teachers, only: [:index, :create]
  end

  # for admins to sign in as teachers
  resources :users do
    member do
      get :admin_sign_in_classroom_manager, to: 'admins#sign_in_classroom_manager'
      get :admin_sign_in_progress_reports, to: 'admins#sign_in_progress_reports'
      get :admin_sign_in_account_settings, to: 'admins#sign_in_account_settings'
    end
  end


  resources :subscriptions
  resources :assessments
  resources :assignments
  resource :profile
  resources :password_reset
  resources :schools, only: [:index], format: 'json'
  resources :unit_templates, only: [:index, :show], format: 'json'

  resources :activity_sessions, only: [] do
    get :anonymous, on: :collection
    get :play, on: :member
    put :play, on: :member
  end
  # 3rd party apps depend on the below, do not change :
  get 'activity_sessions/:uid' => 'activity_sessions#result'


  resources :activities, only: [] do
    post :retry, on: :member
    get :search, on: :collection
  end

  resources :grades, only: [:index]

  get :porthole_proxy, to: 'porthole_proxy#index'

  namespace :teachers do

    resources :units, as: 'units_path'  # moved from within classroom, since units are now cross-classroom

    resources :unit_templates, only: [:index] do
      collection do
        post :fast_assign, controller: 'unit_templates', action: 'fast_assign'
      end
    end

    resources :classroom_activities, only: [:destroy, :update], as: 'classroom_activities_path'


    get 'my_account' => 'classroom_manager#my_account'
    get 'my_account_data' => 'classroom_manager#my_account_data'
    put 'update_my_account' => 'classroom_manager#update_my_account'
    delete 'delete_my_account' => 'classroom_manager#delete_my_account'
    put 'units/:id/hide' => 'units#hide', as: 'hide_units_path'

    namespace :progress_reports do
      resources :activity_sessions, only: [:index]
      resources :csv_exports, only: [:create]

      namespace :concepts do
        resources :students, only: [:index] do
          resources :concepts, only: [:index]
        end
      end

      namespace :standards do
        resources :classrooms, only: [:index] do
          resources :students, controller: "classroom_students", only: [:index] do
            resources :topics, controller: "student_topics", only: [:index]
          end

          resources :topics, controller: "classroom_topics", only: [:index] do
            resources :students, controller: "topic_students", only: [:index]
          end
        end
      end
    end

    resources :classrooms do
      collection do
        get :regenerate_code
        get :lesson_planner, controller: "classroom_manager", action: 'lesson_planner'
        get :scorebook, controller: 'classroom_manager', action: 'scorebook'
        get :scores, controller: 'classroom_manager', action: 'scores'
        get :search_activities, controller: 'classroom_manager', action: 'search_activities'
        get :retrieve_classrooms_for_assigning_activities, controller: 'classroom_manager', action: 'retrieve_classrooms_for_assigning_activities'
        post :assign_activities, controller: 'classroom_manager', action: 'assign_activities'
      end

      member do
        get :hide #I am not sure why, however the first hide request on a classroom is always a get. Subsequent ones are put.
        put :hide
      end

      resources :activities, controller: 'classroom_activities'

      resources :students do
        put :reset_password
      end

      # TODO: abstract this list as well. Duplicated in nav in layout.
      %w(invite_students accounts import).each do |page|
        get page => "classroom_manager##{page}"
      end

    end
  end

  # API routes
  namespace :api do
    namespace :v1 do
      resources :activities,              except: [:index, :new, :edit]
      resources :activity_flags,          only: [:index]
      resources :activity_sessions,       except: [:index, :new, :edit]
      resources :sections,                only: [:index]
      resources :topics,                  only: [:index]
      resources :topic_categories,        only: [:index]
      resources :concepts,                only: [:index, :create]

      resource :me, controller: 'me',     except: [:index, :new, :edit, :destroy]
      resource :ping, controller: 'ping', except: [:index, :new, :edit, :destroy]
      resource :firebase_tokens,          only: [:create]
    end

    # Try to route any GET, DELETE, POST, PUT or PATCH to the proper controller.
    # This converts requests like GET /v1/ping to /api/v1/ping, and also
    # /ping to /api/v1/ping.
    #
    # These routes are lost since they are globs, and thus will match anything
    # not previously matched.
    # [:get, :delete, :post, :put, :patch].each do |method|
    #   match 'v:api/*path', to: redirect("/api/v1/%{path}"), via: method
    #   match '*path', to: redirect("/api/v1/%{path}"), via: method
    # end
  end

  # for some reason, session_path with method :delete does not evaluate correctly in profiles/student.html.erb
  # so we have the patch below:
  get '/session', to: 'sessions#destroy'
  resource :session

  resource :account do
    post :role, to: 'accounts#role'
  end

  get "/auth/google_oauth2/callback" => 'sessions#google'
  get '/auth/clever/callback', to: 'sessions#clever'
  get '/clever/auth_url_details', to: 'clever#auth_url_details'
  get '/auth/failure', to: 'sessions#failure'

  put '/select_school', to: 'accounts#select_school'

  namespace :cms do
    resources :admin_accounts, only: [:index, :create, :update, :destroy]
    resources :admins, only: [:index, :create, :update, :destroy]
    resources :categories
    resources :sections
    resources :activity_classifications
    resources :topics
    resources :topic_categories
    resources :authors, only: [:index, :create, :update, :destroy]
    resources :unit_templates, only: [:index, :create, :update, :destroy]
    resources :unit_template_categories, only: [:index, :create, :update, :destroy]

    resources :activities, path: 'activity_type/:activity_classification_id/activities' do
      resource :data
    end

    resources :users do
      resource :subscription

      collection do
        match 'search' => 'users#search', via: [:get, :post], as: :search
      end
      member do
        get :show_json
        put :sign_in
      end
    end
  end

  # tooltip is just for prototyping tooltip, if its still there you can remove it.
  %w(tooltip press blog_posts supporters middle_school story learning develop mission faq tos privacy activities new impact stats team premium_access premium teacher_resources press_kit play media news).each do |page|
    get page => "pages##{page}", as: "#{page}"
  end
  get 'activities/section/:section_id' => 'pages#activities', as: "activities_section"
  get 'activities/packs' => 'teachers/unit_templates#index'
  get 'activities/packs/:id' => 'teachers/unit_templates#show'

  get 'lessons' => 'pages#activities' # so that old links still work
  get 'about' => 'pages#activities' # so that old links still work

  get 'demo' => 'teachers/progress_reports/standards/classrooms#demo'

  patch 'verify_question' => 'chapter/practice#verify'
  get   'verify_question' => 'chapter/practice#verify_status'
  patch 'cheat'           => 'chapter/practice#cheat'
  get '404' => 'errors#error_404'
  get '500' => 'errors#error_500'

  root to: 'pages#home'

  # http://stackoverflow.com/questions/26130130/what-are-the-routes-i-need-to-set-up-to-preview-emails-using-rails-4-1-actionmai
  get '/lib/mailer_previews' => "rails/mailers#index"
  get '/lib/mailer_previews/*path' => "rails/mailers#preview"

  # catch-all 404
  get '*path', to: 'application#routing_error'
end

app/controllers/teachers/classroom_activities_controller.rb
class Teachers::ClassroomActivitiesController < ApplicationController
  include QuillAuthentication
  respond_to :json

  before_filter :teacher!
  before_filter :authorize!


  def update
    cas = @classroom_activity.unit.classroom_activities.where(activity: @classroom_activity.activity)
    cas.each{|ca| ca.update_attributes(due_date: params[:due_date])}
    render json: {}
  end

  def destroy
    cas = @classroom_activity.unit.classroom_activities.where(activity: @classroom_activity.activity)
    cas.each{|ca| ca.destroy}
    render json: {}
  end

private

  def authorize!
    @classroom_activity = ClassroomActivity.find params[:id]
    if @classroom_activity.classroom.teacher != current_user then auth_failed end
  end

  def classroom_activity_params
    params[:classroom_activity].permit(:due_date, :due_date_string, :choose_everyone, {assigned_student_ids: []}, :unit_id)
  end
end

app/controllers/teachers/classroom_manager_controller.rb
class Teachers::ClassroomManagerController < ApplicationController
  respond_to :json, :html
  before_filter :teacher!
  before_filter :authorize!
  include ScorebookHelper

  def lesson_planner
    if current_user.classrooms.empty?
      redirect_to new_teachers_classroom_path
    else
      @tab = params[:tab] #|| "manageUnits"
      @grade = params[:grade]
      @students_exist = current_user.students.any?
      @last_classroom_name = current_user.classrooms.last.name
      @last_classroom_id = current_user.classrooms.last.id
    end
  end

  def retrieve_classrooms_for_assigning_activities # in response to ajax request
    current_user.classrooms.includes(:students).each do |classroom|
      obj = {
        classroom: classroom,
        students: classroom.students.sort_by(&:sorting_name)
      }
      ( @classrooms_and_their_students ||= [] ).push obj
    end
    #render partial: 'assign', layout: false
    render json: {
      classrooms_and_their_students: @classrooms_and_their_students
    }
  end

  def invite_students
    @classrooms = current_user.classrooms
  end



  def scorebook
    if current_user.classrooms.empty?
      redirect_to new_teachers_classroom_path
    end

    if current_user.students.empty?
      if current_user.classrooms.last.activities.empty?
        redirect_to(controller: "teachers/classroom_manager", action: "lesson_planner", tab: "exploreActivityPacks", grade: current_user.classrooms.last.grade)
      else
        redirect_to teachers_classroom_invite_students_path(current_user.classrooms.last)
      end
    end
  end

  def scores
    classrooms = current_user.classrooms.includes(classroom_activities: [:unit])
    units = classrooms.map(&:classroom_activities).flatten.map(&:unit).uniq.compact

    if params[:no_load_has_ever_occurred_yet] == 'true'
      params[:classroom_id] = current_user.classrooms.first
      was_classroom_selected_in_controller = true
      selected_classroom = Classroom.find params[:classroom_id]
    else
      was_classroom_selected_in_controller = false
      selected_classroom = nil
    end

    scores, is_last_page = current_user.scorebook_scores params[:current_page].to_i, params[:classroom_id], params[:unit_id], params[:begin_date], params[:end_date]

    render json: {
      teacher: Scorebook::TeacherSerializer.new(current_user).as_json(root: false),
      classrooms: classrooms,
      units: units,
      scores: scores,
      is_last_page: is_last_page,
      was_classroom_selected_in_controller: was_classroom_selected_in_controller,
      selected_classroom: selected_classroom
    }
  end

  # needed to simply render a page, lets React.js do the rest
  def my_account
  end

  def my_account_data
    @user = current_user
    render json: @user
  end

  def update_my_account

    # incoming request

    # var data = {
    #   name: this.state.name,
    #   username: this.state.username,
    #   email: this.state.email,
    #   password: this.state.password,
    #   password_confirmation: this.state.passwordConfirmation,
    #   school_id: this.state.selectedSchool.id,
    #   school_options_do_not_apply: this.state.schoolOptionsDoNotApply
    # }

    response = current_user.update_teacher params
    render json: response
  end

  def delete_my_account
    sign_out
    User.find(params[:id]).destroy
    render json: {}
  end

  private

  def authorize!
    if current_user.classrooms.any?
      if params[:classroom_id].present? and params[:classroom_id].length > 0
        @classroom = Classroom.find(params[:classroom_id])
      end

      @classroom ||= current_user.classrooms.first
      auth_failed unless @classroom.teacher == current_user
    end
  end
end

app/controllers/teachers/classrooms_controller.rb
class Teachers::ClassroomsController < ApplicationController
  respond_to :json, :html
  before_filter :teacher!
  before_filter :authorize!

  def index
    if current_user.classrooms.empty?
      redirect_to new_teachers_classroom_path
    else
      @classrooms = current_user.classrooms
      @classroom = @classrooms.first
    end
  end

  def new
    @classroom = current_user.classrooms.new
    @classroom.generate_code
  end

  def regenerate_code
    cl = Classroom.new
    cl.generate_code
    render json: {code: cl.code}
  end

  def create
    @classroom = Classroom.create(classroom_params.merge(teacher: current_user))
    if @classroom.valid?
      ClassroomCreationWorker.perform_async(@classroom.id)
      if current_user.students.empty?
        redirect_to(controller: "teachers/classroom_manager", action: "lesson_planner", tab: "exploreActivityPacks", grade: @classroom.grade)
      else
        redirect_to teachers_classroom_invite_students_path(@classroom)
      end
    else
      render :new
    end
  end

  def update
    @classroom.update_attributes(classroom_params)
    # this is updated from the students tab of the scorebook, so will make sure we keep user there
    redirect_to teachers_classroom_students_path(@classroom.id)
  end

  def destroy
    @classroom.destroy
    redirect_to teachers_classrooms_path
  end

  def hide
    classroom = Classroom.find(params[:id])
    classroom.visible = false #
    classroom.save(validate: false)
    redirect_to teachers_classrooms_path
  end

private

  def classroom_params
    params[:classroom].permit(:name, :code, :grade)
  end

  def authorize!
    return unless params[:id].present?
    @classroom = Classroom.find(params[:id])
    auth_failed unless @classroom.teacher == current_user
  end
end

app/controllers/teachers/progress_reports/activity_sessions_controller.rb
class Teachers::ProgressReports::ActivitySessionsController < Teachers::ProgressReportsController
  def index
    respond_to do |format|
      format.html
      format.json do
        query = ::ProgressReports::ActivitySession.new(current_user).results(params)
        page_count = (query.count / ActivitySession::RESULTS_PER_PAGE.to_f).ceil
        activity_sessions = query.paginate(params[:page], ActivitySession::RESULTS_PER_PAGE)
        activity_session_json = activity_sessions.map do |activity_session|
          ::ProgressReports::ActivitySessionSerializer.new(activity_session).as_json(root: false)
        end
        classrooms = ProgressReports::Standards::Classroom.new(current_user).results({})
        students = ProgressReports::Standards::Student.new(current_user).results({})
        units = ProgressReports::Standards::Unit.new(current_user).results({})
        render json: {
          activity_sessions: activity_session_json,
          classrooms: classrooms,
          students: students,
          page_count: page_count,
          teacher: UserWithEmailSerializer.new(current_user).as_json(root: false),
          units: units
        }
      end
    end
  end
end

app/controllers/teachers/progress_reports/concepts/concepts_controller.rb
class Teachers::ProgressReports::Concepts::ConceptsController < Teachers::ProgressReportsController
  def index
    respond_to do |format|
      format.html do
        @student = student
      end
      format.json do
        render json: json_payload
      end
    end
  end

  private

  def json_payload
    {
      concepts: concepts_as_json,
      student: ::StudentSerializer.new(student).as_json(root: false)
    }
  end

  def concepts
    ::ProgressReports::Concepts::Concept.results(current_user, concept_filters)
  end

  def concept_filters
    { student_id: params[:student_id] }
  end

  def concepts_as_json
    concepts.map do |concept|
      serializer = ::ProgressReports::Concepts::ConceptSerializer.new(concept)
      serializer.as_json(root: false)
    end
  end

  def student
    current_user.students.find(params[:student_id])
  end
end

app/controllers/teachers/progress_reports/concepts/students_controller.rb
class Teachers::ProgressReports::Concepts::StudentsController < Teachers::ProgressReportsController
  def index
    respond_to do |format|
      format.html
      format.json { render json: json_payload }
    end
  end

  private

  def json_payload
    {
      students: students_as_json
    }
  end

  def students_as_json
    ::ProgressReports::Concepts::User.results(current_user, {}).map do |student|
      serializer = ::ProgressReports::Concepts::StudentSerializer.new(student)
      serializer.as_json(root: false)
    end
  end
end

app/views/teachers/classroom_manager/_classroom_selector_and_legend.html.erb
  <div class="invite-students container">

    <section class="section-content-wrapper">

      <div class="row">

        <!-- wrapping the contents of sections and letting them have 75% width -->
        <div class="col-xs-12 col-xl-12 no-pl">

          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-5 col-xl-5 button-select-wrapper select-white-wrapper">

            <div class="button-select">
              <button type="button" class="select-mixin select-white" data-toggle="dropdown">
              <%= @classroom.name %>
              <% unless @classrooms.empty? %><i class="fa fa-caret-down"></i><% end %>
              </button>

              <% unless @classrooms.empty? %>
                <ul class="dropdown-menu" role="menu">
                  <% @classrooms.each do |classroom| %>
                    <li><%= link_to classroom.name, teachers_classroom_scorebook_path(classroom_id: classroom.id) %></li>
                  <% end %>
                </ul>
              <% end %>

            </div>

          </div> <!-- //.col-xs-12 -->

          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 button-select-wrapper select-gray-wrapper no-pl">

            <div class="button-select">
              <button type="button" class="select-mixin select-gray" data-toggle="dropdown">
              <% if @unit %>
                <%= @unit.name %>
              <% else %>
                All Units
              <% end %>
              <% unless @units.empty? %><i class="fa fa-caret-down"></i><% end %>
              </button>

              <% unless @units.empty? %>
                <ul class="dropdown-menu" role="menu">
                  <%= link_to('All Units', teachers_classroom_scorebook_path(@classroom)) if @unit %>
                  <% @units.each do |unit| %>
                    <%= link_to unit.name, teachers_classroom_scorebook_path(classroom_id: @classroom.id, unit_id: unit.id) %>
                  <% end %>
                </ul>
              <% end %>

            </div>

          </div><!-- //.col-xs-12 -->

        </div>  <!-- //.col-xs-9 (parent) -->

      </div><!-- //.row -->

      <div class="icons-wrapper icon-legend">

        <div class="row no-pl">

          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-10 col-xl-10 no-pl">

            <div class="col-xs-6 col-sm-3 col-xl-3">
              <div class="icon-wrapper icon-green"></div>

              <div class="icons-description-wrapper">
                <p class="title">At Proficiency</p>
                <p class="explanation">100-76%</p>
              </div>

            </div> <!-- //first-col -->

            <div class="col-xs-6 col-sm-3 col-xl-3 no-pl">
              <div class="icon-wrapper icon-orange"></div>

              <div class="icons-description-wrapper">
                <p class="title">Nearly Proficient</p>
                <p class="explanation">75-50%</p>
              </div>

            </div> <!-- //second-col -->

            <div class="col-xs-6 col-sm-3 col-xl-3 no-pl">

              <div class="icon-wrapper icon-red"></div>

              <div class="icons-description-wrapper">
                <p class="title">Not Yet Proficient</p>
                <p class="explanation">49-0%</p>
              </div>

            </div> <!-- //third-col-->

            <div class="col-xs-6 col-sm-3 col-xl-3 no-pl">

              <div class="icon-wrapper icon-gray"></div>

              <div class="icons-description-wrapper">
                <p class="title title-not-started">Not Started</p>
              </div>

            </div> <!-- //fourth-col -->

          </div> <!-- //.col-xs-9 (parent) -->

          <div class="col-xs-12 col-md-12 col-lg-2 col-xl-2 no-pl no-pr">

            <div class="how-we-grade">
              <p class="title title-not-started">
                <%= link_to "How We Grade", "/faq" %>
                <a href=""><i class="fa fa-long-arrow-right"></i></a>
              </p> <!-- //.how-we-grade -->
            </div>

          </div> <!-- //.col-xs-3 -->

        </div> <!-- //.row -->

      </div> <!-- //.icons-wrapper -->

    </section>
  </div> <!-- //.container -->

app/views/teachers/classroom_manager/invite_students.html.slim
= render partial: 'teachers/shared/scorebook_tabs'
= render partial: 'teachers/classrooms/subnav'
= javascript_include_tag "add_students.js"

.container.invite-students
  section.no-border
    .row
      .col-xs-12.col-sm-6.col-md-6.col-lg-5.col-xl-5.button-select-wrapper.select-white-wrapper
        .button-select
          button.select-mixin.select-white[type="button" data-toggle="dropdown"]
            = @classroom.name
            - unless @classrooms.empty?
              i.fa.fa-caret-down
          - unless @classrooms.empty?
            ul.dropdown-menu[role="menu"]
              - @classrooms.each do |classroom|
                li= link_to classroom.name,
                            teachers_classroom_invite_students_path(classroom)


    h1.section-header Have Students Create Their Accounts

    ol
      li Have students sign up at quill.org/account/new
      li
        | Once students sign up, in the "Join My Class" field,
          <br>
        ' they enter the class code
        strong= @classroom.code

    span.class-code Class Code
    input[type='text' class='inactive' value=@classroom.code disabled]


    h1.section-header Or You Create Student Accounts

    div
      | The students’ usernames are their names combined with your
      br
      | class code. For example, John Smith is 'John.Smith@
      = @classroom.code
      | '.
      br
      .mt-15
        | Students passwords are set to their last names by default.
        br
        | For example, ‘Smith’ (first letter is capitalized).
    .m-20
      = form_for User.new, url: teachers_classroom_students_path(@classroom), remote: true do |f|
        = f.text_field :first_name, placeholder: 'First Name'
        = f.text_field :last_name, placeholder: 'Last Name'
        = f.submit 'Add Student', class: 'button-green ajax-button'

    table.table.students.hidden
      thead
        tr
          th First Name
          th Last Name
          th Username
      tbody
          - @classroom.students.sort_by(&:sorting_name).each do |student|
            tr class=dom_class(student) id=dom_id(student)
              - %i(first_name last_name username).each do |sym|
                td[class=sym]= student.send(sym)

app/views/teachers/classroom_manager/lesson_planner.html.erb
<%= render partial: 'teachers/shared/scorebook_tabs' %>



<div id="page-content-wrapper">

	<div class="tab-pane" id="activity-planner" data-tab="<%= @tab %>" data-grade="<%= @grade %>" data-students="<%= @students_exist %>" data-classroom-name="<%= @last_classroom_name%>" data-classroom-id="<%= @last_classroom_id%>">
    <%= render partial: 'application/spinner' %>

	<!-- ==========================================================================
		 Progress tracker
		========================================================================== -->

	</div>
</div> <!-- //#page-content-wrapper -->

app/views/teachers/classroom_manager/my_account.html.slim
= render partial: 'teachers/shared/scorebook_tabs'
= render partial: 'teachers/classrooms/subnav'

#my-account

app/views/teachers/classroom_manager/scorebook.html.erb
<%= render partial: 'teachers/shared/scorebook_tabs' %>



<div id="page-content-wrapper">

  <div class="tab-pane" id="scorebook">

    <%= render partial: 'application/spinner' %>

  <!-- ==========================================================================
     Scorebook React code operates here
    ========================================================================== -->

  </div>
</div> <!-- //#page-content-wrapper -->